classes_name_dict = {
    "imagenet_R": {
        "classes": [
            'goldfish',
            'great white shark',
            'hammerhead shark',
            'stingray',
            'hen',
            'ostrich',
            'goldfinch',
            'junco',
            'bald eagle',
            'vulture',
            'smooth newt',
            'axolotl',
            'tree frog',
            'green iguana',
            'chameleon',
            'Indian cobra',
            'scorpion',
            'tarantula',
            'centipede',
            'peafowl',
            'lorikeet',
            'hummingbird',
            'toucan',
            'duck',
            'goose',
            'black swan',
            'koala',
            'jellyfish',
            'snail',
            'American lobster',
            'hermit crab',
            'flamingo',
            'great egret',
            'pelican',
            'king penguin',
            'grey whale',
            'killer whale',
            'sea lion',
            'Chihuahua',
            'Shih Tzu',
            'Afghan Hound',
            'Basset Hound',
            'Beagle',
            'Bloodhound',
            'Italian Greyhound',
            'Whippet',
            'Weimaraner',
            'Yorkshire Terrier',
            'Boston Terrier',
            'Scottish Terrier',
            'West Highland White Terrier',
            'Golden Retriever',
            'Labrador Retriever',
            'Cocker Spaniel',
            'collie',
            'Border Collie',
            'Rottweiler',
            'German Shepherd Dog',
            'Boxer',
            'French Bulldog',
            'St. Bernard',
            'Siberian Husky',
            'Dalmatian',
            'pug',
            'Pomeranian',
            'Chow Chow',
            'Pembroke Welsh Corgi',
            'Toy Poodle',
            'Standard Poodle',
            'grey wolf',
            'hyena',
            'red fox',
            'tabby cat',
            'leopard',
            'snow leopard',
            'lion',
            'tiger',
            'cheetah',
            'polar bear',
            'meerkat',
            'ladybug',
            'fly',
            'bee',
            'ant',
            'grasshopper',
            'cockroach',
            'praying mantis',
            'dragonfly',
            'monarch butterfly',
            'starfish',
            'cottontail rabbit',
            'porcupine',
            'fox squirrel',
            'beaver',
            'guinea pig',
            'zebra',
            'pig',
            'hippopotamus',
            'bison',
            'gazelle',
            'llama',
            'skunk',
            'badger',
            'orangutan',
            'gorilla',
            'chimpanzee',
            'gibbon',
            'baboon',
            'giant panda',
            'eel',
            'clownfish',
            'pufferfish',
            'accordion',
            'ambulance',
            'assault rifle',
            'backpack',
            'barn',
            'wheelbarrow',
            'basketball',
            'bathtub',
            'lighthouse',
            'beer glass',
            'binoculars',
            'birdhouse',
            'bow tie',
            'broom',
            'bucket',
            'cauldron',
            'candle',
            'cannon',
            'canoe',
            'carousel',
            'castle',
            'mobile phone',
            'cowboy hat',
            'electric guitar',
            'fire truck',
            'flute',
            'gas mask or respirator',
            'grand piano',
            'guillotine',
            'hammer',
            'harmonica',
            'harp',
            'hatchet',
            'jeep',
            'joystick',
            'lab coat',
            'lawn mower',
            'lipstick',
            'mailbox',
            'missile',
            'mitten',
            'parachute',
            'pickup truck',
            'pirate ship',
            'revolver',
            'rugby ball',
            'sandal',
            'saxophone',
            'school bus',
            'schooner',
            'shield',
            'soccer ball',
            'space shuttle',
            'spider web',
            'steam locomotive',
            'scarf',
            'submarine',
            'tank',
            'tennis ball',
            'tractor',
            'trombone',
            'vase',
            'violin',
            'military aircraft',
            'wine bottle',
            'ice cream',
            'bagel',
            'pretzel',
            'cheeseburger',
            'hot dog',
            'cabbage',
            'broccoli',
            'cucumber',
            'bell pepper',
            'mushroom',
            'Granny Smith apple',
            'strawberry',
            'lemon',
            'pineapple',
            'banana',
            'pomegranate',
            'pizza',
            'burrito',
            'espresso',
            'volcano',
            'baseball player',
            'scuba diver',
            'acorn',
        ],},
        "imagenet_A": 
        {"classes":
        [
            "stingray",
            "goldfinch",
            "junco",
            "American robin",
            "jay",
            "bald eagle",
            "vulture",
            "newt",
            "American bullfrog",
            "box turtle",
            "green iguana",
            "agama",
            "chameleon",
            "American alligator",
            "garter snake",
            "harvestman",
            "scorpion",
            "tarantula",
            "centipede",
            "sulphur-crested cockatoo",
            "lorikeet",
            "hummingbird",
            "toucan",
            "duck",
            "goose",
            "koala",
            "jellyfish",
            "sea anemone",
            "flatworm",
            "snail",
            "crayfish",
            "hermit crab",
            "flamingo",
            "great egret",
            "oystercatcher",
            "pelican",
            "sea lion",
            "Chihuahua",
            "Golden Retriever",
            "Rottweiler",
            "German Shepherd Dog",
            "pug",
            "red fox",
            "Persian cat",
            "lynx",
            "lion",
            "American black bear",
            "mongoose",
            "ladybug",
            "rhinoceros beetle",
            "weevil",
            "fly",
            "bee",
            "ant",
            "grasshopper",
            "stick insect",
            "cockroach",
            "praying mantis",
            "leafhopper",
            "dragonfly",
            "monarch butterfly",
            "small white butterfly",
            "gossamer-winged butterfly",
            "starfish",
            "cottontail rabbit",
            "porcupine",
            "fox squirrel",
            "marmot",
            "bison",
            "skunk",
            "armadillo",
            "baboon",
            "white-headed capuchin",
            "African bush elephant",
            "pufferfish",
            "academic gown",
            "accordion",
            "acoustic guitar",
            "airliner",
            "ambulance",
            "apron",
            "balance beam",
            "balloon",
            "banjo",
            "barn",
            "wheelbarrow",
            "basketball",
            "lighthouse",
            "beaker",
            "bikini",
            "hunting bow",
            "bow tie",
            "breastplate",
            "broom",
            "candle",
            "canoe",
            "castle",
            "cello",
            "chain",
            "storage chest",
            "Christmas stocking",
            "cowboy boot",
            "cradle",
            "rotary dial telephone",
            "digital clock",
            "doormat",
            "drumstick",
            "dumbbell",
            "envelope",
            "feather boa",
            "flagpole",
            "forklift",
            "fountain",
            "garbage truck",
            "goblet",
            "go-kart",
            "golf cart",
            "grand piano",
            "hair dryer",
            "clothes iron",
            "carved pumpkin",
            "jeep",
            "kimono",
            "lighter",
            "limousine",
            "manhole cover",
            "maraca",
            "marimba",
            "mask",
            "mitten",
            "mosque",
            "metal nail",
            "obelisk",
            "ocarina",
            "pipe organ",
            "parachute",
            "parking meter",
            "piggy bank",
            "pool table",
            "hockey puck",
            "quill",
            "racket",
            "fishing casting reel",
            "revolver",
            "rocking chair",
            "rugby ball",
            "salt shaker",
            "sandal",
            "saxophone",
            "school bus",
            "schooner",
            "sewing machine",
            "shovel",
            "sleeping bag",
            "snowmobile",
            "snowplow",
            "soap dispenser",
            "spatula",
            "spider web",
            "steam locomotive",
            "stethoscope",
            "couch",
            "submarine",
            "sundial",
            "suspension bridge",
            "syringe",
            "tank",
            "teddy bear",
            "toaster",
            "torch",
            "tricycle",
            "umbrella",
            "unicycle",
            "viaduct",
            "volleyball",
            "washing machine",
            "water tower",
            "wine bottle",
            "shipwreck",
            "guacamole",
            "pretzel",
            "cheeseburger",
            "hot dog",
            "broccoli",
            "cucumber",
            "bell pepper",
            "mushroom",
            "lemon",
            "banana",
            "cherimoya (custard apple)",
            "pomegranate",
            "carbonara",
            "bubble",
            "cliff",
            "volcano",
            "baseball player",
            "rapeseed",
            "yellow lady's slipper",
            "corn",
            "acorn",
        ],},
        "cifar100":
        {"classes":
        [
            "apple",
            "aquarium fish",
            "baby",
            "bear",
            "beaver",
            "bed",
            "bee",
            "beetle",
            "bicycle",
            "bottle",
            "bowl",
            "boy",
            "bridge",
            "bus",
            "butterfly",
            "camel",
            "can",
            "castle",
            "caterpillar",
            "cattle",
            "chair",
            "chimpanzee",
            "clock",
            "cloud",
            "cockroach",
            "couch",
            "crab",
            "crocodile",
            "cup",
            "dinosaur",
            "dolphin",
            "elephant",
            "flatfish",
            "forest",
            "fox",
            "girl",
            "hamster",
            "house",
            "kangaroo",
            "keyboard",
            "lamp",
            "lawn mower",
            "leopard",
            "lion",
            "lizard",
            "lobster",
            "man",
            "maple tree",
            "motorcycle",
            "mountain",
            "mouse",
            "mushroom",
            "oak tree",
            "orange",
            "orchid",
            "otter",
            "palm tree",
            "pear",
            "pickup truck",
            "pine tree",
            "plain",
            "plate",
            "poppy",
            "porcupine",
            "possum",
            "rabbit",
            "raccoon",
            "ray",
            "road",
            "rocket",
            "rose",
            "sea",
            "seal",
            "shark",
            "shrew",
            "skunk",
            "skyscraper",
            "snail",
            "snake",
            "spider",
            "squirrel",
            "streetcar",
            "sunflower",
            "sweet pepper",
            "table",
            "tank",
            "telephone",
            "television",
            "tiger",
            "tractor",
            "train",
            "trout",
            "tulip",
            "turtle",
            "wardrobe",
            "whale",
            "willow tree",
            "wolf",
            "woman",
            "worm",
        ]},}