hydra:
  run:
    dir: ./experiments/${scenario}/${dataset}_${initial_increment}-${increment}_without_exp
  job:
    chdir: true

  job_logging:
    version: 1
    formatters:
      simple:
        format: '%(message)s'

class_order: "cifar_order.yaml"
class_order_idx: [0,1,2]
dataset_root: "/data/cifar-100"
workdir: ""
log_path: "metric.json"
log_suffix: "SECA"
model_name: "ViT-B/16"
prompt_template: "a good photo of a {}."

batch_size: 128
initial_increment: 10  
increment: ${initial_increment}
scenario: "class"
dataset: "cifar100"
# Code that generates features and controls the number is too rough :(.
# If you want to change the number of initial and increment and batch size, 
# you should change the beta value and list_for_one_batch in the main code line 78.
# beta *len(list_for_one_batch) * batch_num_per_epoch(relevant to bz) * 10 approximates 2000 , number of samples generated per epoch
num_workers: 16
train_batch_size: 100
fp16: false
seed: 2
beta: 2 
mix_bias: 0.6
threshold: 0.55
shrinkage: false

text_peft_module: "prompt"
prompt_epochs: 3
prompt_lr: 5e-4
prompt_weight_decay: 5e-4
prompt_milestones: [2,10]
prompt_optimizer: "adam"
eval_prompt_tool: "exp_mean"

text_start_block: 0
text_end_block: 11

peft_module: "adapter"
start_block: 0
end_block: 11 
epochs: 3
lr: 0.001
lr_scale: 1.0
milestones: [2,10] 
ensemble_type: "seq"

zero_shot: False
many_templates: False

train_text: True
train_visual: True
visual_first_session: False
co_optimizer: True

## loss functions
loss_kd: True
interm_lr: 0.001
visual_proto: True
post_lr: 0.001
gaussian_sampling: False

train_temperature: 20.0
eval_temperature: 20.0
pool_size: 5